export enum cardsActionTypes {
  REQUEST = 'FETCH_CARDS_REQUEST',
  SUCCESS = 'FETCH_CARDS_SUCCESS',
  FAILURE = 'FETCH_CARDS_FAILURE',
}

export enum singleCardActionTypes {
  REQUEST = 'FETCH_SINGLE_CARD_REQUEST',
  SUCCESS = 'FETCH_SINGLE_CARD_SUCCESS',
  FAILURE = 'FETCH_SINGLE_CARD_FAILURE',
}
