export enum cardbacksActionTypes {
  REQUEST = 'FETCH_CARDBACKS_REQUEST',
  SUCCESS = 'FETCH_CARDBACKS_SUCCESS',
  FAILURE = 'FETCH_CARDBACKS_FAILURE',
  LOAD_MORE_REQUEST = 'FETCH_MORE_CARDBACKS_REQUEST',
  LOAD_MORE_SUCCESS = 'FETCH_MORE_CARDBACKS_SUCCESS',
  LOAD_MORE_FAILURE = 'FETCH_MORE_CARDBACKS_FAILURE',
  SEARCH = 'SEARCH_CARDBACKS',
  FILTER = 'FILTER_CARDBACKS',
}

export enum singleCardbackActionTypes {
  REQUEST = 'FETCH_SINGLE_CARDBACK_REQUEST',
  SUCCESS = 'FETCH_SINGLE_CARDBACK_SUCCESS',
  FAILURE = 'FETCH_SINGLE_CARDBACK_FAILURE',
}
