export enum cardsActionTypes {
  REQUEST = 'FETCH_CARDS_REQUEST',
  SUCCESS = 'FETCH_CARDS_SUCCESS',
  FAILURE = 'FETCH_CARDS_FAILURE',
  LOAD_MORE_REQUEST = 'FETCH_MORE_CARDS_REQUEST',
  LOAD_MORE_SUCCESS = 'FETCH_MORE_CARDS_SUCCESS',
  LOAD_MORE_FAILURE = 'FETCH_MORE_CARDS_FAILURE',
  SEARCH = 'SEARCH_CARDS',
  FILTER = 'FILTER_CARDS',
}

export enum singleCardActionTypes {
  REQUEST = 'FETCH_SINGLE_CARD_REQUEST',
  SUCCESS = 'FETCH_SINGLE_CARD_SUCCESS',
  FAILURE = 'FETCH_SINGLE_CARD_FAILURE',
}
